site_name: LearnSwift - App
nav:
  - Home: index.md
  - Swift: swift.md
  - SwiftUI: swiftUI.md
  - Swift-Quizzes: swiftQuiz.md
  - SwiftUI-Quizzes: swiftUIQuiz.md
  - SwiftUI-Playground Tests: swiftUITests.md
  
